name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: xcodebuild -scheme "XCTest example" -destination 'platform=iOS Simulator,OS=15.2,name=iPod touch (7th generation)'
      
    - name: Run tests
      run: xcodebuild test -scheme 'XCTest example' -destination 'platform=iOS Simulator,name=iPod touch (7th generation)'
